// <auto-generated />
namespace EcommerceApi_dotNetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edited));
        
        string IMigrationMetadata.Id
        {
            get { return "202109151702328_edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
