// <auto-generated />
namespace EcommerceApi_dotNetFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paymentserviecCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paymentserviecCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202109151530287_paymentserviecCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
